// Please do NOT edit this file directlly
// To synchronize set/update project configs:
// + From terminal, run $ sheetbase config set key=value|...
// + Or, edit configs in sheetbase.json, then run $ sheetbase config update
export const SHEETBASE_CONFIG = {
  "backendUrl": "https://script.google.com/macros/s/AKfycbxd9qxwbOl4Oy8nSurN_XyDZOnswOSNm1ZldczCuYyvIbMlrtg/exec"
};
